SELECT B.FOOD_TYPE, A.REST_ID, A.REST_NAME, B.FAVORITES
FROM REST_INFO A
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
     FROM REST_INFO
     GROUP BY FOOD_TYPE)
     AS B
ON A.FOOD_TYPE = B.FOOD_TYPE
AND A.FAVORITES = B.FAVORITES
GROUP BY B.FOOD_TYPE
ORDER BY B.FOOD_TYPE DESC;